# Generated by Django 6.0.2 on 2026-03-27 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_rename_location_company_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='resume',
            field=models.FileField(default='test@gmail.com', upload_to='resumes/'),
            preserve_default=False,
        ),
    ]
