# Generated by Django 6.0.2 on 2026-04-05 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_job_apply_link_alter_job_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='category',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
