# Generated by Django 6.0.2 on 2026-04-05 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_job_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='category',
            new_name='catergory',
        ),
    ]
