# Generated by Django 6.0.2 on 2026-04-05 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_rename_category_job_catergory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='catergory',
            new_name='category',
        ),
    ]
